#!/usr/bin/env bash

# Prompt for user identity + secret configuration.
echo "Please enter your name [Firstname Lastname] and press ENTER"
read NAME

echo "Please enter your @applidget.com email address and press ENTER"
read EMAIL

echo "Please enter the amazon ACCESS key and press ENTER"
read AMAZON_ACCESS_KEY

echo "Please enter the amazon SECRET key and press ENTER"
read AMAZON_SECRET_KEY

echo "Thanks! Starting installation..."

# First check for dependencies
echo "[Dependency] Command Line Tools"
  [[ -f /usr/bin/cc ]] || (echo "You need to download and install Command Line Tools. Look for ctools_lion_*.dmg"; exit)

# Oh-my-zsh
echo "Installing Oh-my-zsh, to enhance your shell ..."
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

# Setup SSH
echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/settings/ssh

# Install Stuff
echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='~/bin:/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Configuring git ..."
  git config --global color.ui true
  git config --global core.editor vim
  git config --global alias.co checkout
  git config --global alias.st status
  git config --global alias.br branch
  git config --global user.name "$NAME"
  git config --global user.email $EMAIL

mkdir -p ~/Library/LaunchAgents # Will put startup scripts here

echo "Installing Redis, a good key-value database ..."
  brew install redis
  echo "Configuring Redis so that it starts at startup ..."
  REDIS_CURRENT_PLIST=~/Library/LaunchAgents/homebrew.mxcl.redis.plist
  [[ -f ~/.ssh/id_rsa.pub ]] || launchctl unload -w REDIS_CURRENT_PLIST
  
  REDIS_PLIST=`ls /usr/local/Cellar/redis/*/homebrew.mxcl.redis.plist | tail -1`
  echo "Copying $REDIS_PLIST to ~/Library/LaunchAgents/"
  cp $REDIS_PLIST ~/Library/LaunchAgents/  
  launchctl load -w $REDIS_CURRENT_PLIST

echo "Installing MongoDB, a good NoSQL database ..."
  brew install mongodb
  echo "Configuring MongoDB so that it starts at startup ..."
  MONGO_CURRENT_PLIST=~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
  [[ -f ~/.ssh/id_rsa.pub ]] || launchctl unload -w $MONGO_CURRENT_PLIST
  
  MONGO_PLIST=`ls /usr/local/Cellar/mongodb/*/homebrew.mxcl.mongodb.plist | tail -1`
  MONGO_CONFIG=`ls /usr/local/Cellar/mongodb/*/mongod.conf | tail -1`
  echo "Copying $MONGO_PLIST to ~/Library/LaunchAgents/"
  echo "Copying $MONGO_CONFIG to /usr/local/etc/"
  cp $MONGO_PLIST ~/Library/LaunchAgents/
  [[ -f /data/db ]] (echo "Need your password to sudo to create the folder /data/db"; sudo mkdir -p /data/db; sudo chown `id -u` /data/db)
  cp MONGO_CONFIG /usr/local/etc/mongod.conf
  launchctl load -w $MONGO_CURRENT_PLIST 

echo "Installing NodeJS ..."
  curl http://npmjs.org/install.sh | sh

echo "Installing ack, a good way to search through files ..."
  brew install ack
  
echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing automake, which is need for doing rvm install --with-gcc=clang"
  brew install automake

echo "Installing RVM (Ruby Version Manager) ..."
  bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc

bash < <(curl -s https://raw.github.com/applidget/laptop/master/ruby)
bash < <(curl -s https://raw.github.com/applidget/laptop/master/heroku)


echo "Adding useful aliases and Applidget's configuration ..."
  echo "

# Email (for ruby applications in dev mode)
export EMAIL=$EMAIL

# Amazon
export AMAZON_ACCESS_KEY=$AMAZON_ACCESS_KEY
export AMAZON_SECRET_KEY=$AMAZON_SECRET_KEY

# Auto CD
setopt auto_cd
cd_path=(~) # TODO: add your regularly used directories

# Applidget aliases
alias rspec='bundle exec rspec spec --color'" >> ~/.zshrc
  source ~/.zshrc

echo "You can run vim ~/.zshrc to customize it, and use those recommended settings:"
echo "-----------------------------"
echo 'ZSH_THEME="kphoen"'
echo 'plugins=(git github osx ruby)'
echo "-----------------------------"
echo " "
echo "Your mac is now setup, you can do some work now :) Welcome to Applidget!"
